# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
    - repo: https://github.com/python-poetry/poetry
      rev: 1.8.2
      hooks:
        - id: poetry-check
        - id: poetry-lock
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.0
      hooks:
        - id: ruff
        - id: ruff-format
    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.0
      hooks:
          - id: nbstripout
